### ISSUE TITLE
Can't evaluate ''#{(1)}

### ISSUE THREAD

**Issue by amalloy** [Raynes/clojail#1]
If the code passed to `sandbox` contains a quoted set which contains a list, there are errors about read-eval. Moving the quote inside the set so that it's in front of the list, ie `'#{'(1)}`, resolves the issue. Needs more investigation to find out what's going wrong.

**Comment by Raynes** [comment]
I can't reproduce this anymore (assuming I ever did?). Closing.

**Comment by amalloy** [comment]
We did repro at some point, but I can't remember exactly what the test-case was. It's in a 4clojure Issue somewhere; i'll take a look.

**Comment by dbyrne** [comment]
Link to the 4clojure issue: https://github.com/4clojure/4clojure/issues/67

**Comment by Raynes** [comment]
I've been unable to reproduce this myself. If anybody can come up with a repro case that doesn't involve 4Clojure, please reply.
