### ISSUE TITLE
Definitions fail after if more than 5 functions defined?..

### ISSUE THREAD

**Issue by ifesdjeen** [Raynes/clojail#5]
I'm trying to define several (more than 5, let's say functions):

``` clj
(deftest sanbox-defns-test
  (let [sb (sandbox [])]
    (sb '(defn a1 [] 1))
    (sb '(defn a2 [] 1))
    (sb '(defn a3 [] 1))
    (sb '(defn a4 [] 1))
    (sb '(defn a5 [] 1))
    (sb '(defn a6 [] 1))
    (sb '(defn a7 [] 1))
    (sb '(defn a8 [] 1))
    (sb '(defn a9 [] 1))

    (println (sb '(keys (ns-publics *ns*))))
))
```

Interestingly, I get:

``` clj
(a9 tester1972 a6 dot a8 a7)
```

Any ideas what may cause such a behavior?..

**Comment by ifesdjeen** [comment]
nevermind, it's `max-defs` default...

**Comment by Raynes** [comment]
Clojail has mechanisms in place to limit the number of defined thing.

When defining the sandbox, you can pass a `:max-defs` option to set the limit on the defs. I don't think there anything to say "infinite", but you can probably just set that number to a billion (or positive infinity, :p) and be on your merry way.

**Comment by ifesdjeen** [comment]
:+1: thanks!
